import { ref, computed } from '@vue/reactivity';
import { defineStore } from 'pinia';
import type { PokemonCard } from '../types';

export const useMainStore = defineStore('main', () => {
  // const count = ref(0)
  // const doubleCount = computed(() => count.value * 2)
  // function increment() {
  //   count.value++
  // }
  const pokemons = ref<PokemonCard[]>([
    {
      id: '1',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '2',
      name: 'chandelure',
      types: ['poison', 'grass'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '3',
      name: 'chandelure',
      types: ['fire', 'flying'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '4',
      name: 'chandelure',
      types: ['water', 'bug'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '5',
      name: 'chandelure',
      types: ['fairy', 'ground'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '6',
      name: 'chandelure',
      types: ['rock', 'normal'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '7',
      name: 'chandelure',
      types: ['psychic', 'steel'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '8',
      name: 'chandelure',
      types: ['dragon', 'dark'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '9',
      name: 'chandelure',
      types: ['ghost', 'ice'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '10',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '11',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '12',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '13',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '14',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
    {
      id: '15',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      height: 0,
      weight: 0,
      abilities: [],
    },
  ]);

  const favourite = ref<{ id: string; state: boolean }[]>([
    { id: '1', state: false },
    { id: '2', state: false },
    { id: '3', state: false },
    { id: '4', state: false },
    { id: '5', state: false },
    { id: '6', state: false },
    { id: '7', state: false },
    { id: '8', state: false },
    { id: '9', state: false },
    { id: '10', state: false },
    { id: '11', state: false },
    { id: '12', state: false },
    { id: '13', state: false },
    { id: '14', state: false },
    { id: '15', state: false },
  ]);

  const page = ref(0);

  return { pokemons, favourite, page };
});
