import { ref, computed } from '@vue/reactivity';
import { defineStore } from 'pinia';
import type { PokemonCard } from '../types';

export const useMainStore = defineStore('main', () => {
  const spread = ref<Record<string, string[]>>({
    kanto: ['chandelure'],
    johto: ['chandelure'],
    hoenn: ['chandelure'],
    sinnoh: ['chandelure'],
    unova: ['chandelure'],
    kalos: ['chandelure'],
    alola: ['chandelure'],
    galar: ['chandelure'],
    hisui: ['chandelure'],
    paldea: ['chandelure'],
  });

  const pokemons = ref<PokemonCard[]>([
    {
      id: '1',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '2',
      name: 'chandelure',
      types: ['poison', 'grass'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '3',
      name: 'chandelure',
      types: ['fire', 'flying'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '4',
      name: 'chandelure',
      types: ['water', 'bug'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '5',
      name: 'chandelure',
      types: ['fairy', 'ground'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '6',
      name: 'chandelure',
      types: ['rock', 'normal'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '7',
      name: 'chandelure',
      types: ['psychic', 'steel'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '8',
      name: 'chandelure',
      types: ['dragon', 'dark'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '9',
      name: 'chandelure',
      types: ['ghost', 'ice'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '10',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '11',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '12',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '13',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '14',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
    {
      id: '15',
      name: 'chandelure',
      types: ['electric', 'fighting'],
      image: 'alola-01.avif',
      gif: '',
      description: '',
      detail: {
        ability: [],
        weight: '',
        height: '',
        spread: [],
      },
    },
  ]);

  const favourite = ref<{ id: string; state: boolean }[]>([
    { id: '1', state: false },
    { id: '2', state: false },
    { id: '3', state: false },
    { id: '4', state: false },
    { id: '5', state: false },
    { id: '6', state: false },
    { id: '7', state: false },
    { id: '8', state: false },
    { id: '9', state: false },
    { id: '10', state: false },
    { id: '11', state: false },
    { id: '12', state: false },
    { id: '13', state: false },
    { id: '14', state: false },
    { id: '15', state: false },
  ]);

  const pokemon = ref({
    id: '1',
    name: 'Bulbasaur',
    types: ['grass', 'poison'],
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id, recusandae deleniti natus quod tempore officiis odio. Vel quisquam quas aliquam voluptatum reiciendis quaerat cumque? Aut voluptates minima repellendus alias ea?',
    detail: {
      weight: 6.9,
      height: 0.7,
      spread: ['Kanto', 'Johto'],
      ability: ['Overgrow', 'Poison'],
    },
    gif: 'alola-01.avif',
    femalePossibility: 0.2,
    weakness: ['electric', 'psychic', 'flying', 'fighting'],
    evolution: [
      {
        id: '1',
        image: 'alola-01.avif',
        name: 'Bulbasaur',
        minLevel: 0,
        types: ['grass', 'poison'],
      },
      {
        id: '2',
        image: 'alola-01.avif',
        name: 'Ivysaur',
        minLevel: 16,
        types: ['grass', 'poison'],
      },
      {
        id: '3',
        image: 'alola-01.avif',
        name: 'Venusaur',
        minLevel: 36,
        types: ['grass', 'poison'],
      },
    ],
    favourite: false,
  });

  const page = ref(0);

  return { spread, pokemons, pokemon, favourite, page };
});
